version: 2
updates:

  # Enable version updates for composer
  - package-ecosystem: "composer"
    directory: "/src" 
    schedule:
      interval: "daily"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "daily"
