version: 2

updates:
  # Enable version updates for composer
  - package-ecosystem: "composer"
    directory: "/src" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    versioning-strategy: auto
